// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url:"mongodb+srv://tokagawaMarketing:tokagawaMarketing@cluster0.0xqiyz1.mongodb.net/hospitalkiosk?appName=Cluster0&retryWrites=true&w=majority",
  },
});
